### ISSUE TITLE
LogIn

### ISSUE THREAD

**Issue by Natural-H** [Natural-H/project-manager#1]
What it should do:
1. Allow Internal Advisors to log in, they should use their username and password, and store a token as a cookie to keep their session up.
2. Show their home page, there their active projects will be listed.

Considerations:
1. It *may* expand (if time allows it) to be used by Students and External Advisors as well to log in, so keep that in mind.

**Comment by esalu-dev** [comment]
Should it be a unified login (in case of including students and external advisors)?

**Comment by Natural-H** [comment]
Yeah
